# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbank_id', models.CharField(max_length=50, unique=True)),
                ('qbank_file', models.FileField(upload_to='qbs/')),
                ('ans_file', models.FileField(upload_to='ans/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('test', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50, unique=True)),
                ('request', models.IntegerField(default=0)),
                ('checked', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('qbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Qbank')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='qbank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.User'),
        ),
    ]
