# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(default='Empty', max_length=150)),
                ('ques', models.CharField(default='Empty', max_length=150)),
                ('ans', models.CharField(default='Empty', max_length=1500)),
            ],
        ),
    ]
