# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='qno',
            field=models.IntegerField(default=0),
        ),
    ]
