# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_temp_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_pass',
            field=models.CharField(default='imbatman', max_length=50),
        ),
    ]
