# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_test_test_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=101)),
            ],
        ),
    ]
