# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0006_testlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlog',
            name='score',
            field=models.CharField(default='not checked', max_length=50),
        ),
    ]
