# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_testlog_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlog',
            name='user_id',
            field=models.CharField(default='EMPTY', max_length=50),
            preserve_default=False,
        ),
    ]
